[package]
name = "rs-store"
# 0.18.0 add store metrics
version = "0.18.0"
edition = "2021"
authors = ["Changju Lee", "Changju Lee<rookiecj@gmail.com>"]
description = "Redux Store for Rust"
license-file = "LICENSE"
#homepage="https://github.com/rookiecj/rs-store"
#documentation="https://docs.rs/rs-store"
repository = "https://github.com/rookiecj/rs-store"
readme = "README.md"
keywords = ["redux", "store", "rust", "state", "management"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.58"
crossbeam = "0.8"
lazy_static = "1.4"
rusty_pool = { version = "0.7" }

# [[bin]]
# name = "calc_basic"
# path = "examples/calc_basic.rs"

# [[bin]]
# name = "calc_fn_basic"
# path = "examples/calc_fn_basic.rs"

# [[bin]]
# name = "calc_concurrent"
# path = "examples/calc_concurrent.rs"

# [[bin]]
# name = "calc_unsubscribe"
# path = "examples/calc_unsubscribe.rs"

# [[bin]]
# name = "calc_clear_subscriber"
# path = "examples/calc_clear_subscribers.rs"

# [[bin]]
# name = "calc_thunk"
# path = "examples/calc_thunk.rs"

# [[bin]]
# name = "calc_effect"
# path = "examples/calc_effect.rs"

# [[bin]]
# name = "calc_basic_builder"
# path = "examples/calc_basic_builder.rs"
