[package]
name = "store-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.58"
once_cell = "1.19.0"


[[bin]]
name = "calc"
path = "src/example/calc.rs"

[[bin]]
name = "calc_fn"
path = "src/example/calc_fn.rs"
