[package]
name = "rs-store"
# 0.21.0 add get_metrics
version = "0.21.0"
edition = "2021"
authors = ["Changju Lee", "Changju Lee<rookiecj@gmail.com>"]
description = "Redux Store for Rust"
license-file = "LICENSE"
#homepage="https://github.com/rookiecj/rs-store"
#documentation="https://docs.rs/rs-store"
repository = "https://github.com/rookiecj/rs-store"
readme = "README.md"
keywords = ["redux", "store", "rust", "state", "management"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
notify-channel = []

[dependencies]
thiserror = "1.0.58"
crossbeam = "0.8"
rusty_pool = { version = "0.7" }
