[package]
name = "rs-store"
version = "0.4.1"
edition = "2021"
authors = ["Changju Lee", "Changju Lee<rookiecj@gmail.com>"]
description = "Redux Store for Rust"
license-file = "LICENSE"
#homepage="https://github.com/rookiecj/rs-store"
#documentation="https://docs.rs/rs-store"
repository = "https://github.com/rookiecj/rs-store"
readme = "README.md"
keywords = ["redux", "store", "rust", "state", "management"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.58"
once_cell = "1.19.0"

[[bin]]
name = "calc_basic"
path = "src/example/calc_basic.rs"

[[bin]]
name = "calc_fn_basic"
path = "src/example/calc_fn_basic.rs"
